export {AboutPage} from './AboutPage'
export {HeroPage} from './HeroPage'
export {ContactPage} from './ContactPage'
export {DentistsPage} from './DentistsPage'
export {WorkPage} from './WorkPage'
export {PostPage} from './PostPage'
export {BlogPage} from './blogpage/BlogPage'
export {GalleryPage} from './gallery/GalleryPage.js'